## NUMPY ARRAY AND VECTORIZATION

In [1]:
import numpy as np
arr = [2,5,6,7]
print(type(arr))

<class 'list'>


In [2]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
print(a.dtype)

int32


In [7]:
#dimension of a
print(a.ndim)

1


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
print(b.shape)
print(b.dtype)
print(b.ndim)

(2, 3)
int32
2


### Inbuilt functions to initialize  numpy

In [15]:
# a 2x3 array with random values
np.random.random((2,3))

array([[0.41088869, 0.97716231, 0.53487445],
       [0.11092408, 0.49130009, 0.55622892]])

In [17]:
# a 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# a 2x3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### INTRA OPERABILITY OF ARRAYS AND SCALARS

Vectorisation in numpy arrays allows for faster processing by eliminating for loops when dealing with arrays of equal shape. This allows for batch arithmetic operations on the arrays by applying the operator elementwise.

Similarly, scalars are also propagated element-wise across an array.

For arrays with different sizes, it is impossible to perform element-wise operations instead; numpy handles this by broadcasting provided the dimensions of the arrays are the same or, one of the dimensions of the array is 1.

In [21]:
c = np.array([[2.0,7.0,9.0],[1.0,3.0,5.0]])
d = np.array([[3.0,8.0,5.0],[6.0,4.0,2.0]])


In [22]:
print(c+d)

[[ 5. 15. 14.]
 [ 7.  7.  7.]]


In [23]:
print(c*d)

[[ 6. 56. 45.]
 [ 6. 12. 10.]]


In [24]:
print(5/d)

[[1.66666667 0.625      1.        ]
 [0.83333333 1.25       2.5       ]]


In [25]:
print(c ** 2)

[[ 4. 49. 81.]
 [ 1.  9. 25.]]


### INDEXING WITH ARRAYS AND USING ARRAYS FOR DATA PROCESSING

In [26]:
print(a)

[2 5 6 7]


In [27]:
a[0]

2

In [28]:
a[-1]

7

In [29]:
a[3]

7

In [30]:
print(b)

[[1 2 3]
 [4 5 6]]


In [31]:
b[0,0]

1

In [32]:
b[-1,-1]

6

In [33]:
b[ :-1]

array([[1, 2, 3]])

In [34]:
b[1,2]

6

In [36]:
print(d)

[[3. 8. 5.]
 [6. 4. 2.]]


In [37]:
d[1, 0:2]

array([6., 4.])

In [38]:
d[:3, :2]

array([[3., 8.],
       [6., 4.]])

Numpy also has inbuilt mathematical functions like sum(), mean(), std(), corrcoef(), min() and others. 

In [39]:
d.sum()

28.0

In [40]:
d.mean()

4.666666666666667

In [41]:
d.std()

1.9720265943665387

In [43]:
d.min()

2.0

In [44]:
d==b

array([[False, False, False],
       [False, False, False]])

#### File Input and Output With Arrays

Numpy arrays can be loaded from and saved to binary files with .npy as the extension using load() and save() respectively. This can also be done with text files with text files using loadtxt() and savetxt().